# Generated by Django 4.1.5 on 2023-02-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
