# Generated by Django 4.1.5 on 2023-02-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_otp_alter_profile_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='duration',
            field=models.DurationField(),
        ),
    ]
