# Generated by Django 4.1.5 on 2023-02-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_otp_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Period'),
        ),
    ]
