# Generated by Django 4.1.5 on 2023-02-15 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_profile_otp_otp_created_otp_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='users.profile'),
        ),
    ]
