# Generated by Django 4.1.5 on 2023-02-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_otp_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='duration',
        ),
    ]
