# Generated by Django 4.1.5 on 2023-02-18 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_remove_otp_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='workers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to=settings.AUTH_USER_MODEL),
        ),
    ]
