insert into db.sqlite3 (name, in_stock, category, price, create) values ('Clam Nectar', 11, 'Men', 1, '1/7/2023');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Cheese - Bakers Cream Cheese', 28, 'Men', 8, '7/11/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Salmon Atl.whole 8 - 10 Lb', 94, 'Women', 18, '11/19/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Wine - Niagara,vqa Reisling', 99, 'Children', 1, '3/12/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Muffin - Blueberry Individual', 57, 'Children', 65, '3/4/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Savory', 72, 'Children', 59, '3/15/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Venison - Ground', 30, 'Children', 4, '4/1/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Gherkin', 52, 'Children', 77, '1/9/2023');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Cheese - Cheddar, Medium', 100, 'Children', 69, '3/26/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Soup - Tomato Mush. Florentine', 18, 'Men', 5, '6/23/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Dc Hikiage Hira Huba', 49, 'Children', 7, '1/31/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Muffin Mix - Blueberry', 69, 'Children', 75, '4/4/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Basil - Pesto Sauce', 5, 'Children', 86, '4/5/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Vermouth - White, Cinzano', 69, 'Children', 58, '7/11/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Cilantro / Coriander - Fresh', 49, 'Women', 66, '5/8/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Milk - Buttermilk', 82, 'Children', 39, '12/29/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Oven Mitts 17 Inch', 67, 'Children', 75, '1/27/2023');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Beef - Bones, Cut - Up', 46, 'Children', 55, '1/15/2023');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Shiro Miso', 64, 'Children', 9, '10/18/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Wine - Cahors Ac 2000, Clos', 57, 'Men', 42, '7/2/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Juice - Apple 284ml', 45, 'Children', 16, '12/14/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Melon - Watermelon, Seedless', 92, 'Men', 76, '3/16/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Container - Hngd Cll Blk 7x7x3', 99, 'Children', 100, '11/18/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Tarts Assorted', 69, 'Children', 91, '7/18/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Nut - Hazelnut, Ground, Natural', 87, 'Children', 92, '2/10/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Coffee Guatemala Dark', 56, 'Women', 87, '7/11/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Soup - Campbells Bean Medley', 68, 'Children', 10, '4/4/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Cake - Cake Sheet Macaroon', 10, 'Children', 78, '8/26/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Bread - Bistro Sour', 69, 'Men', 45, '11/18/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Swordfish Loin Portions', 54, 'Children', 51, '4/27/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Artichoke - Hearts, Canned', 81, 'Men', 63, '9/19/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('V8 Splash Strawberry Banana', 83, 'Men', 44, '2/8/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Wine - Cotes Du Rhone', 16, 'Children', 72, '5/4/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Saskatoon Berries - Frozen', 87, 'Children', 76, '5/5/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Hog / Sausage Casing - Pork', 79, 'Children', 70, '1/24/2023');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Olives - Black, Pitted', 93, 'Women', 28, '9/30/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Soup - Campbells Tomato Ravioli', 79, 'Men', 39, '12/15/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Squid - Tubes / Tenticles 10/20', 81, 'Children', 15, '9/29/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Apple - Delicious, Golden', 10, 'Children', 77, '8/15/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Wine - Acient Coast Caberne', 54, 'Women', 90, '11/7/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Tart Shells - Sweet, 2', 72, 'Children', 95, '3/9/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Star Anise, Whole', 15, 'Men', 41, '6/5/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Lotus Rootlets - Canned', 7, 'Children', 63, '7/20/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Carbonated Water - Peach', 63, 'Children', 75, '12/18/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Dragon Fruit', 57, 'Children', 42, '2/7/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Eggs - Extra Large', 20, 'Men', 78, '11/18/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Corn - Mini', 60, 'Men', 62, '11/14/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Wine - White, Riesling, Henry Of', 15, 'Women', 91, '8/19/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Beer - Blue Light', 50, 'Children', 20, '11/25/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Dill Weed - Fresh', 99, 'Children', 16, '8/12/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Wine - Chablis 2003 Champs', 70, 'Children', 88, '7/26/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Appetizer - Tarragon Chicken', 47, 'Women', 55, '12/7/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Sprouts - Alfalfa', 86, 'Women', 19, '5/29/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Pastry - Trippleberry Muffin - Mini', 9, 'Women', 17, '7/16/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Tea - Grapefruit Green Tea', 29, 'Women', 86, '5/27/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Snapple Raspberry Tea', 75, 'Children', 14, '9/28/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Raisin - Dark', 79, 'Children', 31, '1/15/2023');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Muffin Chocolate Individual Wrap', 98, 'Children', 9, '2/9/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Lid Coffeecup 12oz D9542b', 68, 'Men', 10, '1/11/2023');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Cheese - Comtomme', 24, 'Children', 80, '4/2/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Veal - Nuckle', 76, 'Children', 90, '4/21/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Wine - Merlot Vina Carmen', 11, 'Women', 98, '7/23/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Sugar - Fine', 4, 'Men', 50, '10/3/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Rhubarb', 9, 'Women', 42, '4/15/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Wine - Chablis J Moreau Et Fils', 49, 'Children', 27, '7/4/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Rum - Dark, Bacardi, Black', 99, 'Women', 60, '7/15/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Beer - Upper Canada Lager', 52, 'Women', 92, '2/5/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Lettuce - Arugula', 95, 'Children', 73, '3/30/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Radish - Black, Winter, Organic', 27, 'Children', 95, '2/18/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Arctic Char - Fillets', 35, 'Women', 43, '2/2/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Oil - Macadamia', 25, 'Children', 43, '1/9/2023');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Yucca', 75, 'Men', 87, '4/19/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Pasta - Lasagna Noodle, Frozen', 8, 'Women', 51, '1/18/2023');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Energy Drink Red Bull', 65, 'Children', 96, '6/9/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Plastic Wrap', 80, 'Women', 68, '12/3/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Crush - Orange, 355ml', 17, 'Children', 92, '4/29/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Parsley - Fresh', 16, 'Children', 95, '9/5/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Wine - Red, Black Opal Shiraz', 27, 'Women', 47, '11/16/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Vodka - Lemon, Absolut', 98, 'Men', 82, '9/15/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Nut - Pine Nuts, Whole', 6, 'Children', 36, '7/19/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Cilantro / Coriander - Fresh', 55, 'Children', 62, '9/19/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Mustard - Individual Pkg', 47, 'Children', 25, '6/16/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Flour - Masa De Harina Mexican', 34, 'Men', 73, '10/27/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Vermouth - White, Cinzano', 42, 'Children', 39, '7/21/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Pastry - Chocolate Marble Tea', 83, 'Women', 12, '4/15/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Wine - Chateau Timberlay', 11, 'Children', 30, '10/6/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Bar Bran Honey Nut', 30, 'Children', 79, '9/10/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Flour - Strong', 81, 'Children', 74, '12/23/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Loquat', 30, 'Women', 52, '6/26/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Pork Loin Bine - In Frenched', 47, 'Children', 51, '3/27/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Horseradish - Prepared', 43, 'Men', 3, '7/14/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Creamers - 10%', 82, 'Women', 15, '2/11/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Pastry - Banana Tea Loaf', 79, 'Women', 67, '5/23/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Tarts Assorted', 7, 'Children', 26, '2/19/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Sauce - Apple, Unsweetened', 38, 'Men', 3, '4/2/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Compound - Mocha', 89, 'Children', 10, '11/19/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Chinese Foods - Plain Fried Rice', 26, 'Children', 67, '8/4/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Potatoes - Fingerling 4 Oz', 59, 'Children', 73, '8/16/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Coffee Swiss Choc Almond', 32, 'Children', 38, '3/21/2022');
insert into db.sqlite3 (name, in_stock, category, price, create) values ('Shark - Loin', 50, 'Children', 82, '7/3/2022');