# Generated by Django 4.1.5 on 2023-03-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='state_ID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
