# Generated by Django 4.1.5 on 2023-03-31 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUnauthenticated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=300, null=True)),
                ('zipcode', models.CharField(max_length=10, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_reviewed', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopUnauthVerifyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('forshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopdocs', to='shop.shopunauthenticated')),
            ],
        ),
    ]
