# Generated by Django 4.1.5 on 2023-03-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopunauthenticated',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
